#!/usr/bin/env bash
# M3 rig: a real `hermes serve` (password provider, approvals=manual) backed by
# the mock inference server, in an isolated HERMES_HOME. The phone or the
# vitest live tests talk to it like any gateway.
#
#   apps/mobile/testing/rig.sh [bind-host] [port] [hermes-home]
#
# Env: HERMES_PY (python with hermes deps; default: the installed venv),
#      RIG_USER / RIG_PASSWORD / RIG_SECRET for the basic-auth provider.
set -euo pipefail
HOST="${1:-0.0.0.0}"
PORT="${2:-9137}"
HOME_DIR="${3:-/tmp/hermes-m3-home}"
MOCK_PORT="${MOCK_PORT:-9977}"
REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
PY="${HERMES_PY:-$HOME/.hermes/hermes-agent/venv/bin/python}"

mkdir -p "$HOME_DIR"
cat > "$HOME_DIR/config.yaml" <<YAML
# Generated by apps/mobile/testing/rig.sh
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: http://127.0.0.1:${MOCK_PORT}/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 4096
auxiliary:
  title_generation:
    enabled: false
approvals:
  mode: "manual"
YAML
printf 'MOCK_API_KEY=m3-mock-key\n' > "$HOME_DIR/.env"

node "$REPO/apps/mobile/testing/mock-inference.mjs" "$MOCK_PORT" &
MOCK_PID=$!
trap 'kill $MOCK_PID 2>/dev/null || true' EXIT

export HERMES_HOME="$HOME_DIR"
export HERMES_SERVE_HEADLESS=1
export HERMES_DASHBOARD_BASIC_AUTH_USERNAME="${RIG_USER:-spike}"
export HERMES_DASHBOARD_BASIC_AUTH_PASSWORD="${RIG_PASSWORD:-m0-spike-password}"
export HERMES_DASHBOARD_BASIC_AUTH_SECRET="${RIG_SECRET:-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}"
cd "$REPO"
exec "$PY" hermes serve --host "$HOST" --port "$PORT" --skip-build
